---
title: "Arve"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: hide
date: "2025-06-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, error = F, fig.align = "center", collapse = T,
                      cache = T)
```

```{r libraries}
library(ggplot2)
library(dplyr)
library(readxl)
library(lubridate)
```

# Getting data

```{r load-data-from-excel, message = F}

cmes <- readxl::read_xlsx(path = "arve.xlsx", sheet = "CMES", col_types = c("date","numeric","text")) %>% subset(Qualite == "v") %>% mutate(Qualite = NULL)
fmes <- readxl::read_xlsx(path = "arve.xlsx", sheet = "FMES", col_types = c("date","numeric","text")) %>% subset(Qualite == "v") %>% mutate(Qualite = NULL)

poc <- readxl::read_xlsx(path = "arve.xlsx", sheet = "POC", col_types = c("date","date","numeric","text")) %>% subset(Qualite == "v") %>% mutate(Qualite = NULL)
poc$poc_timeinterval <- poc$Debut %--% poc$Fin

debit <- readxl::read_xlsx(path = "arve.xlsx", sheet = "Debit", col_types = c("date","numeric")) %>% mutate(Statut = NULL) %>% setNames(c("DateHeure","q_m3.s")) %>%
  unique()


```

```{r join-debit-poc}
na_interval <- poc$Fin[dim(poc)[1]] %--% poc$Debut[1]  %>% as.character()

# poc$poc_timeinterval[debit$DateHeure[100] >= poc$Debut & debit$DateHeure[100] <= poc$Fin]

debit_timeinterval <- sapply(debit$DateHeure, FUN = function (x){as.character(poc$poc_timeinterval[x >= poc$Debut & x <= poc$Fin])}, simplify = T)
na_timeinterval <- which(lengths(debit_timeinterval) == 0)
debit_timeinterval[na_timeinterval] <- na_interval

debit_timeinterval[which(lapply(debit_timeinterval, length) != 1)] <- debit_timeinterval[which(lapply(debit_timeinterval, length) != 1)][[1]]

debit$poc_timeinterval <- do.call(c, (debit_timeinterval))
```

```{r merge}
arve <- merge(debit, cmes, by = "DateHeure", all = T) %>% merge(poc, by = "poc_timeinterval", all = T) %>% unique()

arve$year <- year(arve$DateHeure)
arve$commondate <- as.Date(paste0("2000-", format(arve$DateHeure,"%j")), "%Y-%j")
arve$Date <- format(arve$DateHeure, "%Y-%m-%d")
```


```{r poc-cmes}
ggplot(arve)+
  geom_segment(aes(x=Debut, xend = Fin, y = poc_g.kg, yend = poc_g.kg, col = "POC"), size = 2)+
  geom_segment(aes(x=Debut, xend = Debut, y = 0, yend = poc_g.kg, col = "POC"), alpha = 0.5, size = 0.1)+
   geom_segment(aes(x=Fin, xend = Fin, y = 0, yend = poc_g.kg, col = "POC"), alpha = 0.5, size = 0.1)+
  geom_point(aes(x = DateHeure, y = cmes_mg.L/100, col = "CMES"),size = 0.5)+ # to plot with secondary axis scale
  scale_color_manual(values = c("palegreen4", "lightblue"))+
  scale_y_continuous( name = "POC, g/kg", sec.axis = sec_axis(~.*100, name = "CMES, mg/L"))+
  theme_minimal()+
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90))
```

```{r plot-mean-Q}
meanQcommondate <- arve %>% group_by(commondate) %>% summarise(meanQ = mean(q_m3.s, na.rm = T))

ggplot()+geom_line(data = arve, aes(x=commondate, y = q_m3.s, group = year, col = as.character(year)), alpha = 0.2)+
  geom_line(data = meanQcommondate, aes(x=commondate, y = meanQ), col = "black")+
  scale_color_viridis_d(option = "G", end = 0.8)+
  labs(x = "", y = "Débit, m3/s", col = "")+
  scale_x_date(labels = function(x) format(x, "%d-%b"), date_minor_breaks = "1 month")+
  theme_minimal()+
  theme(legend.position = "bottom")

```



```{r cmes-interpol}
arve$cmes_interpol <- imputeTS::na_interpolation(arve$cmes_mg.L, maxgap = 24)

ggplot(arve, aes(x=q_m3.s))+ 
  geom_point(aes(y= cmes_mg.L, col = "measured"), alpha = 0.5, size = 1) +
  geom_point(aes(y = cmes_interpol, col = "interpol"), alpha = 0.5, size = 0.5)+
  labs(title = "", x = "Débit, mg/L", y = "MES, mg/L")+
  scale_color_manual(values = c("lightblue","palegreen4"))+
  theme_minimal()+
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90))

ggplot(arve, aes(x=DateHeure))+ 
  geom_point(aes(y= cmes_mg.L, col = "measured"), alpha = 0.5, size = 1) +
  geom_point(aes(y = cmes_interpol, col = "interpol"), alpha = 0.5, size = 0.5)+
  labs(title = "", x = "Date", y = "MES, mg/L")+
  scale_color_manual(values = c("lightblue","palegreen4"))+
  theme_minimal()+
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90))
```

```{r poc-mg-L}
arve$poc_mg.L <- with(arve, cmes_interpol*1e-6*poc_g.kg*1e3) # CMES converted from mg/L to kg/L, POC obtained in g is converted to mg
arve$fpoc_kg.h <- with(arve, q_m3.s * 1e3 * poc_mg.L * 3600 * 1e-6) # discharge converted from m3/s to L/h; fPOC is obtained in mg/L/s and converted to kg/h

ggplot()+ 
  geom_point(data = subset(arve, !is.na(cmes_mg.L)),aes(x=commondate, y= fpoc_kg.h, col = "POC flux"), alpha = 0.5, size = 0.5) +
  geom_point(data = subset(arve, !is.na(cmes_mg.L)),aes(x=commondate, y= cmes_interpol*q_m3.s*1e3*3600*1e-6, col = "CMES interpol"), alpha = 0.5, size = 0.5) +
  scale_y_continuous(transform = "log10")+
  scale_x_date(labels = function(x) format(x, "%d-%b"), date_minor_breaks = "1 month", name = "")+
  scale_color_manual(values = c("palegreen4","lightblue"), name = "")+
  facet_grid(rows = vars(year))+
  theme_minimal()+
  theme(legend.position = "bottom")
```

```{r calcul-yearly-flux} 
yearly_fluxes <- arve %>% 
                  group_by(year) %>% 
                    summarise(fpoc_kg.year = sum(fpoc_kg.h, na.rm = T), 
                              percent_poc_included = sum(!is.na(fpoc_kg.h))/n()*100,
                              nb_days_sampled = length(unique(Date)),
                              nb_days_sampled_poc = length(unique(Date[!is.na(fpoc_kg.h)])),
                              sum_discharge.year = sum(q_m3.s[!is.na(fpoc_kg.h)], na.rm = T),  # faut-il inclure les débits correspondants à des heures où le POC n'est pas mesuré?
                              mean_discharge.year = mean(q_m3.s[!is.na(fpoc_kg.h)], na.rm = T), 
                              sd_discharge.year = sd(q_m3.s[!is.na(fpoc_kg.h)], na.rm = T)) 
# discharge is converted from m3/s to L/h before being summed, as in the formula for fpoc

bv <- 2083
  
# fluxes by adding all hourly fluxes, with uncertainty depending on the nb of observations per year
yearly_fluxes$fpoc_kg.year.km2 <- yearly_fluxes$fpoc_kg.year/bv

# fluxes with ponderation method @Nemery2013 citing Walling and Webb 1985
yearly_fluxes$fpoc_ww_kg.year.km2 <- with(yearly_fluxes, fpoc_kg.year/sum_discharge.year*mean_discharge.year) * 24 * 365 / bv
```

the weight method works if all discharge values are included not only those with a poc value??

```{r figures-flux} 
yearly_fluxes$year <- as.character(yearly_fluxes$year)
yearly_fluxes %>% dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>% knitr::kable() %>% kableExtra::kable_styling()
```

```{r compare-fluxes}
yearly_fluxes$label <- paste(round(yearly_fluxes$nb_days_sampled,2), "days q\n", round(yearly_fluxes$nb_days_sampled_poc,2), " days poc")
ggplot(yearly_fluxes, aes(x = year))+
  geom_col(aes(y = fpoc_kg.year.km2, fill = "POC flux as sum"), position = position_nudge(-0.2), width = 0.4)+
  geom_col(aes(y = fpoc_ww_kg.year.km2, fill = "POC flux as weigthed"), position = position_nudge(0.2), width = 0.4)+
  geom_label(aes(x = year, y = fpoc_ww_kg.year.km2, label = label), nudge_y = 1000, size = 3)+
 # scale_x_continuous(breaks = c(unique(yearly_fluxes$year)), minor_breaks = NULL)+
  scale_size_continuous(range = c(0.1,10))+
  scale_fill_manual(values = c("palegreen4", "lightblue"))+
  labs(x = "", fill = "", y = "Flux de POC, kg/year/km2")+
  theme_minimal()+
  theme(legend.position = "bottom", text = element_text(size = 10))
```

```{r yf}
yf <- yearly_fluxes %>% subset(year %in% c(2012,2013,2014))

yf %>% dplyr::mutate_if(is.numeric, funs(as.character(signif(., 3)))) %>% knitr::kable() %>% kableExtra::kable_styling()
```

```{r compare-fluxes-nona}
yf$label <- paste(round(yf$nb_days_sampled,2), "days q\n", round(yf$nb_days_sampled_poc,2), " days poc")
ggplot(yf, aes(x = year))+
  geom_col(aes(y = fpoc_kg.year.km2, fill = "POC flux as sum"), position = position_nudge(-0.2), width = 0.4)+
  geom_col(aes(y = fpoc_ww_kg.year.km2, fill = "POC flux as weigthed"), position = position_nudge(0.2), width = 0.4)+
  geom_label(aes(x = year, y = fpoc_ww_kg.year.km2, label = label), nudge_y = 1000, size = 3)+
 # scale_x_continuous(breaks = c(unique(yearly_fluxes$year)), minor_breaks = NULL)+
  scale_size_continuous(range = c(0.1,10))+
  scale_fill_manual(values = c("palegreen4", "lightblue"))+
  labs(x = "", fill = "", y = "Flux de POC, kg/year/km2")+
  theme_minimal()+
  theme(legend.position = "bottom", text = element_text(size = 10))
```

```{r interrannual-fluxes}

mixedfluxes_mean <- with(yf, ifelse(nb_days_sampled_poc < 200, fpoc_ww_kg.year.km2, fpoc_kg.year.km2)) %>% mean()
mixedfluxes_sd <- with(yf, ifelse(nb_days_sampled_poc < 200, fpoc_ww_kg.year.km2, fpoc_kg.year.km2)) %>% sd()

means <- data.frame(
  "Mean FPOC sum, kg/year/m2" = mean(yf$fpoc_kg.year.km2),
  "Sd FPOC sum" = sd(yf$fpoc_kg.year.km2),
  "Mean FPOC weighted, kg/m2/year" = mean(yf$fpoc_ww_kg.year.km2, na.rm = T),
  "Sd FPOC weighted" = sd(yf$fpoc_ww_kg.year.km2, na.rm = T),
  "Mean FPOC mixed" = mixedfluxes_mean,
  "Sd FPOC mixed" = mixedfluxes_sd
)

knitr::kable(t(means), digits = 3) %>% kableExtra::kable_styling()
```